<a href="https://colab.research.google.com/github/LastCodeBender42/TensorFlow-Notebooks/blob/main/Practice_Coding_TF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
# Create a vector and verify the rank
mat=tf.constant([1,2,3,4,5,6])
mat, tf.rank(mat)

(<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [ ]:
# Expand the original vector mat on the first axis and verify rank --> creates a matrix
mat2=tf.expand_dims(mat, axis=0)
mat2, tf.rank(mat2)

(<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [ ]:
# Expand the matrix mat2 on the first axis and verify rank --> creates a tensor
mat3=tf.expand_dims(mat2, axis=0)
mat3, tf.rank(mat3)

(<tf.Tensor: shape=(1, 1, 6), dtype=int32, numpy=array([[[1, 2, 3, 4, 5, 6]]], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>)

---

In [ ]:
# Create a matrix and verify the rank
mat=tf.constant([[1,2,3],[4,5,6]])
mat, tf.rank(mat)

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [ ]:
# Expand the matrix mat on the first axis and verify rank --> creates a tensor
mat2=tf.expand_dims(mat, axis=0)
mat2, tf.rank(mat2)

(<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
 array([[[1, 2, 3],
         [4, 5, 6]]], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>)

In [ ]:
# Expand the tensor mat2 on the first axis and verify rank
mat3=tf.expand_dims(mat2, axis=0)
mat3, tf.rank(mat3)

(<tf.Tensor: shape=(1, 1, 2, 3), dtype=int32, numpy=
 array([[[[1, 2, 3],
          [4, 5, 6]]]], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [ ]:
# Expand the tensor mat3 on the first axis and verify rank
mat4=tf.expand_dims(mat3, axis=0)
mat4, tf.rank(mat4)

(<tf.Tensor: shape=(1, 1, 1, 2, 3), dtype=int32, numpy=
 array([[[[[1, 2, 3],
           [4, 5, 6]]]]], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=5>)

The dimensions refer to the axes of the tensor, not to the square brackets themselves. Each axis corresponds to a level of nesting in the tensor structure. Here's how the dimensions align with the tensor:

- The first dimension (1) corresponds to the outermost set of square brackets.
- The second dimension (1) corresponds to the next level of square brackets.
- The third dimension (1) corresponds to the next level of square brackets.
- The fourth dimension (2) corresponds to the innermost set of square brackets, representing the rows of the matrix.
- The fifth dimension (3) corresponds to the elements within each row, representing the columns of the matrix.

So, in summary, the shape `(1, 1, 1, 2, 3)` indicates that the tensor has five dimensions, with a single element along each dimension. The last two dimensions (2 and 3) represent the shape of the innermost structure, which is a 2x3 matrix.

---

In [ ]:
# Create a tensor and verify the shape
mat = tf.constant([[[[1,2,3,4],[5,6,7,8]]],[[[9,10,11,12],[13,14,15,16]]]])
mat, tf.rank(mat)

(<tf.Tensor: shape=(2, 1, 2, 4), dtype=int32, numpy=
 array([[[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8]]],
 
 
        [[[ 9, 10, 11, 12],
          [13, 14, 15, 16]]]], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>)

The shape `(2, 1, 2, 4)` represents a tensor with four dimensions. Let's break down the interpretation of each dimension:

- **First dimension (2)**: This dimension represents the batch size. In this case, there are 2 batches.

- **Second dimension (1)**: This dimension represents the number of elements along the first axis.

- **Third dimension (2)**: This dimension represents the number of elements along the second axis.

- **Fourth dimension (4)**: This dimension represents the number of elements along the third axis.

To better understand this shape, let's visualize how the tensor is structured:

```
[
  [  # First batch
    [
      [  # First element along the second axis
        [a, b, c, d],  # First element along the third axis
        [e, f, g, h]   # Second element along the third axis
      ]
    ]
  ],
  [  # Second batch
    [
      [  # First element along the second axis
        [i, j, k, l],  # First element along the third axis
        [m, n, o, p]   # Second element along the third axis
      ]
    ]
  ]
]
```

In this tensor:

- There are 2 batches.
- Each batch contains a single element along the first axis.
- Each element along the first axis consists of 2 elements along the second axis.
- Each element along the second axis consists of a 2x4 matrix (4 elements along the third axis).

---

In [ ]:
# Create a tensor and verify the shape
mat = tf.constant([[[[1,2,3,4],[5,6,7,8]]],[[[9,10,11,12],[13,14,15,16]]],[[[17,18,19,20],[21,22,23,24]]]])
mat, tf.rank(mat)

(<tf.Tensor: shape=(3, 1, 2, 4), dtype=int32, numpy=
 array([[[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8]]],
 
 
        [[[ 9, 10, 11, 12],
          [13, 14, 15, 16]]],
 
 
        [[[17, 18, 19, 20],
          [21, 22, 23, 24]]]], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>)

The provided tensor is a 4-dimensional tensor. Let's break down its structure and interpret its shape `(3, 1, 2, 4)`:

- **First dimension (3)**: This dimension represents the batch size. In this case, there are 3 batches.

- **Second dimension (1)**: This dimension represents the number of elements along the first axis.

- **Third dimension (2)**: This dimension represents the number of elements along the second axis.

- **Fourth dimension (4)**: This dimension represents the number of elements along the third axis.

To visualize the structure of the tensor:

```
[
  [  # First batch
    [  # First element along the second axis
      [1, 2, 3, 4],  # First element along the third axis
      [5, 6, 7, 8]   # Second element along the third axis
    ]
  ],
  [  # Second batch
    [  # First element along the second axis
      [9, 10, 11, 12],  # First element along the third axis
      [13, 14, 15, 16]  # Second element along the third axis
    ]
  ],
  [  # Third batch
    [  # First element along the second axis
      [17, 18, 19, 20],  # First element along the third axis
      [21, 22, 23, 24]   # Second element along the third axis
    ]
  ]
]
```

In this tensor:

- There are 3 batches.
- Each batch contains a single element along the first axis.
- Each element along the first axis consists of 2 elements along the second axis.
- Each element along the second axis consists of a 2x4 matrix (4 elements along the third axis).

---

In [ ]:
tensor=tf.constant([1,2,3,4,5,6])
new_shape = (2, 3)  # Example new shape: 2 rows, 3 columns
reshaped_tensor = tf.reshape(tensor, (2, 3))
reshaped_tensor


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
tensor = tf.constant([[[[1,2,3,4],[5,6,7,8]]],[[[9,10,11,12],[13,14,15,16]]],[[[17,18,19,20],[21,22,23,24]]]])
tf.shape(tensor), tf.reshape(tensor, (1,3,2,4))

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 1, 2, 4], dtype=int32)>,
 <tf.Tensor: shape=(1, 3, 2, 4), dtype=int32, numpy=
 array([[[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8]],
 
         [[ 9, 10, 11, 12],
          [13, 14, 15, 16]],
 
         [[17, 18, 19, 20],
          [21, 22, 23, 24]]]], dtype=int32)>)

In [ ]:
tensor = tf.constant([[[[1,2,3,4],[5,6,7,8]]],[[[9,10,11,12],[13,14,15,16]]],[[[17,18,19,20],[21,22,23,24]]]])
tf.reshape(tensor, (1,1,6,4))

<tf.Tensor: shape=(1, 1, 6, 4), dtype=int32, numpy=
array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]]], dtype=int32)>

In [ ]:
tensor = tf.constant([[[[1,2,3,4],[5,6,7,8]]],[[[9,10,11,12],[13,14,15,16]]],[[[17,18,19,20],[21,22,23,24]]]])
tf.reshape(tensor, (1,6,4))

<tf.Tensor: shape=(1, 6, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
tensor = tf.constant([[[[1,2,3,4],[5,6,7,8]]],[[[9,10,11,12],[13,14,15,16]]],[[[17,18,19,20],[21,22,23,24]]]])
tf.reshape(tensor, (6,4))

<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]], dtype=int32)>

In [ ]:
tensor = tf.constant([[[[1,2,3,4],[5,6,7,8]]],[[[9,10,11,12],[13,14,15,16]]],[[[17,18,19,20],[21,22,23,24]]]])
tf.reshape(tensor, (2,12)), tf.reshape(tensor, (1,24)), tf.reshape(tensor, (24))

(<tf.Tensor: shape=(2, 12), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(1, 24), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
         17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

---

In [ ]:
import numpy as np
import tensorflow as tf

# Generate synthetic data
np.random.seed(0)
X = np.random.rand(100, 3)  # Generate 100 random samples with 3 features each
true_weights = np.random.rand(3)  # Generate random true weights
true_bias = np.random.rand()  # Generate random true bias
y = np.dot(X, true_weights) + true_bias  # Generate corresponding output labels for linear regression

# Define the linear regression model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(units=1, input_shape=[3])  # Single dense layer for linear regression with input shape of [3]
])

# Compile the model
model.compile(optimizer='sgd', loss='mean_squared_error')

# Train the model
model.fit(X, y, epochs=1000, verbose=0)  # Train for 1000 epochs

# Get the learned weights and bias
learned_weights, learned_bias = model.get_weights()

# Print the learned weights and bias
print("True Weights:", true_weights)
print("Learned Weights:", learned_weights)
print("True Bias:", true_bias)
print("Learned Bias:", learned_bias)


True Weights: [0.9065555  0.77404733 0.33314515]
Learned Weights: [[0.9069988]
 [0.7718629]
 [0.329194 ]]
True Bias: 0.08110138998799676
Learned Bias: [0.08410087]


In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# Make predictions on the training data
y_pred = model.predict(X)

# Calculate mean squared error (MSE)
mse = mean_squared_error(y, y_pred)

# Calculate mean absolute error (MAE)
mae = mean_absolute_error(y, y_pred)

# Calculate R^2 score
r2 = r2_score(y, y_pred)

# Print the error metrics
print("Mean Squared Error (MSE):", mse)
print("Mean Absolute Error (MAE):", mae)
print("R^2 Score:", r2)


4/4 [==============================] - 0s 2ms/step
Mean Squared Error (MSE): 1.4872090415010522e-06
Mean Absolute Error (MAE): 0.000996864702538301
R^2 Score: 0.9999891245479309


In [ ]:
true_weights

array([2, 3, 4])